@echo off
REM ================================================================
REM SpineSCAN FYP — Train _reduce_noise Variants
REM ================================================================
REM Retrains models with noisy labels removed from training data.
REM Requires: results/noisy_target_level_th08.csv, th09.csv, 1016.csv
REM           (generated by src/noise_detection.py)
REM
REM Run from: SpineSCAN_FYP\scripts directory
REM Prereqs:  conda activate rsna
REM           python src/noise_detection.py already run successfully
REM
REM Estimated time: ~10-15h on RTX 4060 8GB
REM ================================================================

setlocal enabledelayedexpansion
set FOLD=0
set REPO=..\spine_model
set LOGFILE=noise_reduction_%date:~-4,4%%date:~-10,2%%date:~-7,2%_%time:~0,2%%time:~3,2%.log

echo ================================================================
echo  SpineSCAN — Noise Reduction Training
echo  Started: %date% %time%
echo  Log: %LOGFILE%
echo ================================================================

pushd %REPO%
if errorlevel 1 (
    echo [FATAL] Cannot cd into %REPO%. Aborting.
    exit /b 1
)

REM Verify noise CSVs exist
if not exist results\noisy_target_level_th08.csv (
    echo [FATAL] results\noisy_target_level_th08.csv not found.
    echo         Run: python src/noise_detection.py
    popd
    exit /b 1
)
if not exist results\noisy_target_level_1016.csv (
    echo [FATAL] results\noisy_target_level_1016.csv not found.
    popd
    exit /b 1
)

REM ── HIGH PRIORITY: Base 5 models with noise reduction ──────────

echo.
echo [1/10] Sagittal Spinal crop_x03_y07 (reduce_noise)
echo ────────────────────────────────────────────────────
if exist results\rsna_saggital_mil_spinal_crop_x03_y07_reduce_noise\fold_0.ckpt (
    echo [SKIP] rsna_saggital_mil_spinal_crop_x03_y07_reduce_noise already trained
) else (
    powershell -Command "python train_one_fold.py -c rsna_saggital_mil_spinal_crop_x03_y07_reduce_noise -f %FOLD% 2>&1 | Tee-Object -FilePath '../%LOGFILE%' -Append"
    if errorlevel 1 echo [WARN] Training failed
)
if exist results\rsna_saggital_mil_spinal_crop_x03_y07_reduce_noise\oof_fold0.csv (
    echo [SKIP] predictions already exist
) else (
    powershell -Command "python predict.py -c rsna_saggital_mil_spinal_crop_x03_y07_reduce_noise -f %FOLD% 2>&1 | Tee-Object -FilePath '../%LOGFILE%' -Append"
)

echo.
echo [2/10] Sagittal NFN crop_x07_y1_v2 (reduce_noise)
echo ────────────────────────────────────────────────────
if exist results\rsna_saggital_mil_nfn_crop_x07_y1_v2_reduce_noise\fold_0.ckpt (
    echo [SKIP] rsna_saggital_mil_nfn_crop_x07_y1_v2_reduce_noise already trained
) else (
    powershell -Command "python train_one_fold.py -c rsna_saggital_mil_nfn_crop_x07_y1_v2_reduce_noise -f %FOLD% 2>&1 | Tee-Object -FilePath '../%LOGFILE%' -Append"
    if errorlevel 1 echo [WARN] Training failed
)
if exist results\rsna_saggital_mil_nfn_crop_x07_y1_v2_reduce_noise\oof_fold0.csv (
    echo [SKIP] predictions already exist
) else (
    powershell -Command "python predict.py -c rsna_saggital_mil_nfn_crop_x07_y1_v2_reduce_noise -f %FOLD% 2>&1 | Tee-Object -FilePath '../%LOGFILE%' -Append"
)

echo.
echo [3/10] Sagittal SS crop_x03_y07_96 (reduce_noise)
echo ────────────────────────────────────────────────────
if exist results\rsna_saggital_mil_ss_crop_x03_y07_96_reduce_noise\fold_0.ckpt (
    echo [SKIP] rsna_saggital_mil_ss_crop_x03_y07_96_reduce_noise already trained
) else (
    powershell -Command "python train_one_fold.py -c rsna_saggital_mil_ss_crop_x03_y07_96_reduce_noise -f %FOLD% 2>&1 | Tee-Object -FilePath '../%LOGFILE%' -Append"
    if errorlevel 1 echo [WARN] Training failed
)
if exist results\rsna_saggital_mil_ss_crop_x03_y07_96_reduce_noise\oof_fold0.csv (
    echo [SKIP] predictions already exist
) else (
    powershell -Command "python predict.py -c rsna_saggital_mil_ss_crop_x03_y07_96_reduce_noise -f %FOLD% 2>&1 | Tee-Object -FilePath '../%LOGFILE%' -Append"
)

echo.
echo [4/10] Axial Spinal crop_x1_y2 (reduce_noise)
echo ────────────────────────────────────────────────────
if exist results\rsna_axial_spinal_dis3_crop_x1_y2_reduce_noise\fold_0.ckpt (
    echo [SKIP] rsna_axial_spinal_dis3_crop_x1_y2_reduce_noise already trained
) else (
    powershell -Command "python train_one_fold.py -c rsna_axial_spinal_dis3_crop_x1_y2_reduce_noise -f %FOLD% 2>&1 | Tee-Object -FilePath '../%LOGFILE%' -Append"
    if errorlevel 1 echo [WARN] Training failed
)
if exist results\rsna_axial_spinal_dis3_crop_x1_y2_reduce_noise\oof_fold0.csv (
    echo [SKIP] predictions already exist
) else (
    powershell -Command "python predict.py -c rsna_axial_spinal_dis3_crop_x1_y2_reduce_noise -f %FOLD% 2>&1 | Tee-Object -FilePath '../%LOGFILE%' -Append"
)

echo.
echo [5/10] Axial NFN+SS x2_y2 (reduce_noise)
echo ────────────────────────────────────────────────────
if exist results\rsna_axial_ss_nfn_x2_y2_center_pad0_reduce_noise\fold_0.ckpt (
    echo [SKIP] rsna_axial_ss_nfn_x2_y2_center_pad0_reduce_noise already trained
) else (
    powershell -Command "python train_one_fold.py -c rsna_axial_ss_nfn_x2_y2_center_pad0_reduce_noise -f %FOLD% 2>&1 | Tee-Object -FilePath '../%LOGFILE%' -Append"
    if errorlevel 1 echo [WARN] Training failed
)
if exist results\rsna_axial_ss_nfn_x2_y2_center_pad0_reduce_noise\oof_fold0.csv (
    echo [SKIP] predictions already exist
) else (
    powershell -Command "python predict.py -c rsna_axial_ss_nfn_x2_y2_center_pad0_reduce_noise -f %FOLD% 2>&1 | Tee-Object -FilePath '../%LOGFILE%' -Append"
)

REM ── ADDITIONAL: Extra crop variants with noise reduction ───────

echo.
echo [6/10] Sagittal Spinal crop_x03_y05 (reduce_noise)
echo ────────────────────────────────────────────────────
if exist results\rsna_saggital_mil_spinal_crop_x03_y05_reduce_noise\fold_0.ckpt (
    echo [SKIP] rsna_saggital_mil_spinal_crop_x03_y05_reduce_noise already trained
) else (
    powershell -Command "python train_one_fold.py -c rsna_saggital_mil_spinal_crop_x03_y05_reduce_noise -f %FOLD% 2>&1 | Tee-Object -FilePath '../%LOGFILE%' -Append"
    if errorlevel 1 echo [WARN] Training failed
)
if exist results\rsna_saggital_mil_spinal_crop_x03_y05_reduce_noise\oof_fold0.csv (
    echo [SKIP] predictions already exist
) else (
    powershell -Command "python predict.py -c rsna_saggital_mil_spinal_crop_x03_y05_reduce_noise -f %FOLD% 2>&1 | Tee-Object -FilePath '../%LOGFILE%' -Append"
)

echo.
echo [7/10] Sagittal NFN crop_x15_y1_v2 (reduce_noise)
echo ────────────────────────────────────────────────────
if exist results\rsna_saggital_mil_nfn_crop_x15_y1_v2_reduce_noise\fold_0.ckpt (
    echo [SKIP] rsna_saggital_mil_nfn_crop_x15_y1_v2_reduce_noise already trained
) else (
    powershell -Command "python train_one_fold.py -c rsna_saggital_mil_nfn_crop_x15_y1_v2_reduce_noise -f %FOLD% 2>&1 | Tee-Object -FilePath '../%LOGFILE%' -Append"
    if errorlevel 1 echo [WARN] Training failed
)
if exist results\rsna_saggital_mil_nfn_crop_x15_y1_v2_reduce_noise\oof_fold0.csv (
    echo [SKIP] predictions already exist
) else (
    powershell -Command "python predict.py -c rsna_saggital_mil_nfn_crop_x15_y1_v2_reduce_noise -f %FOLD% 2>&1 | Tee-Object -FilePath '../%LOGFILE%' -Append"
)

echo.
echo [8/10] Sagittal NFN crop_x03_y1_v2 (reduce_noise)
echo ────────────────────────────────────────────────────
if exist results\rsna_saggital_mil_nfn_crop_x03_y1_v2_reduce_noise\fold_0.ckpt (
    echo [SKIP] rsna_saggital_mil_nfn_crop_x03_y1_v2_reduce_noise already trained
) else (
    powershell -Command "python train_one_fold.py -c rsna_saggital_mil_nfn_crop_x03_y1_v2_reduce_noise -f %FOLD% 2>&1 | Tee-Object -FilePath '../%LOGFILE%' -Append"
    if errorlevel 1 echo [WARN] Training failed
)
if exist results\rsna_saggital_mil_nfn_crop_x03_y1_v2_reduce_noise\oof_fold0.csv (
    echo [SKIP] predictions already exist
) else (
    powershell -Command "python predict.py -c rsna_saggital_mil_nfn_crop_x03_y1_v2_reduce_noise -f %FOLD% 2>&1 | Tee-Object -FilePath '../%LOGFILE%' -Append"
)

echo.
echo [9/10] Sagittal SS crop_x03_y05_96 (reduce_noise)
echo ────────────────────────────────────────────────────
if exist results\rsna_saggital_mil_ss_crop_x03_y05_96_reduce_noise\fold_0.ckpt (
    echo [SKIP] rsna_saggital_mil_ss_crop_x03_y05_96_reduce_noise already trained
) else (
    powershell -Command "python train_one_fold.py -c rsna_saggital_mil_ss_crop_x03_y05_96_reduce_noise -f %FOLD% 2>&1 | Tee-Object -FilePath '../%LOGFILE%' -Append"
    if errorlevel 1 echo [WARN] Training failed
)
if exist results\rsna_saggital_mil_ss_crop_x03_y05_96_reduce_noise\oof_fold0.csv (
    echo [SKIP] predictions already exist
) else (
    powershell -Command "python predict.py -c rsna_saggital_mil_ss_crop_x03_y05_96_reduce_noise -f %FOLD% 2>&1 | Tee-Object -FilePath '../%LOGFILE%' -Append"
)

echo.
echo [10/10] Axial Spinal crop_x05_y6 (reduce_noise)
echo ────────────────────────────────────────────────────
if exist results\rsna_axial_spinal_dis3_crop_x05_y6_reduce_noise\fold_0.ckpt (
    echo [SKIP] rsna_axial_spinal_dis3_crop_x05_y6_reduce_noise already trained
) else (
    powershell -Command "python train_one_fold.py -c rsna_axial_spinal_dis3_crop_x05_y6_reduce_noise -f %FOLD% 2>&1 | Tee-Object -FilePath '../%LOGFILE%' -Append"
    if errorlevel 1 echo [WARN] Training failed
)
if exist results\rsna_axial_spinal_dis3_crop_x05_y6_reduce_noise\oof_fold0.csv (
    echo [SKIP] predictions already exist
) else (
    powershell -Command "python predict.py -c rsna_axial_spinal_dis3_crop_x05_y6_reduce_noise -f %FOLD% 2>&1 | Tee-Object -FilePath '../%LOGFILE%' -Append"
)

popd

echo.
echo ================================================================
echo  Noise reduction training complete!  %date% %time%
echo  Verify checkpoints:
echo    dir %REPO%\results\*reduce_noise\fold_0.ckpt
echo ================================================================
